baseURL = 'https://vjabrayilov.github.io/notes/'
languageCode = 'en-us'
title = 'Workflow'
theme = 'archie'

# Main menu Items


[[menu.main]]
name = "All posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
