baseURL = 'https://vjabrayilov.github.io/notes'
languageCode = 'en-us'
title = 'Workflow'
theme = 'archie'

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
